# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.sdo
canonical: https://interop.esante.gouv.fr/ig/fhir/sdo # the last part of canonical and id must be the same
name: SuiviDecisionsOrientation
title: Médicosocial - Suivi Décisions Orientation
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: draft
version: 4.0.2-ballot-3 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2023+
dependencies:
    ans.fr.nos: 1.1.0
releaseLabel: trial-use
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'
    path-resource:
        - input/FHIR

pages:
    index.md:
        title: Accueil     
    liste_profils.md:
        title: Liste des profils  
    correspondance_objet.md:
        title: Correspondance entre objets métier et ressources du standard HL7 FHIR 
    contenu_dossier.md:
        title: Contenu du dossier
    synthese_flux.md:
        title: Synthèse des flux
    st_flux1.md:
        title: Flux 1 - Recherche et consultation de personne orientée et décision
    st_flux2.md:
        title: Flux 2 - Accord
    st_flux3.md:
        title: Flux 3 - Recherche et résultats d'évaluation
    st_flux4.md:
        title: Flux 4 - StatutPersonneOrientee
    st_flux5.md:
        title: Flux 5 - Recherche et résultats de statuts
    ressource_cda.md: 
        title: Ressources CDA
    securite.md:
        title: Sécurité
    downloads.md:
        title: Téléchargements et usages  
    about.md:
        title: A propos de ce guide
    annexes_Glossaire.md:
        title: Glossaire associé à la spécification
    annexes_Nomenclature.md:
        title: Nomenclatures de référence associées aux spécifications
    annexes_Nomenclatures_precision.md:
        title: Nomenclature précisions de l'orientation
    annexes_OID_MDPH.md:
        title: OID MDPH associés à la spécification
    annexes_Diagramme.md:
        title: Diagramme de Séquence SI-MDPH / SI-SDO / SI-ESMS
    
menu:
    Accueil: index.html
    Contenu du dossier : contenu_dossier.html
    Description des flux:
        Correspondance entre objets métier et ressources du standard HL7 FHIR: correspondance_objet.html
        Synthèse des flux: synthese_flux.html
        Flux 1 - Recherche et consultation de personne orientée et décision: st_flux1.html
        Flux 2 - Accord: st_flux2.html
        Flux 3 - Recherche et résultats d'évaluation: st_flux3.html
        Flux 4 - StatutPersonneOrientee: st_flux4.html
        Flux 5 - Recherche et résultats de statut: st_flux5.html
    Ressources de conformité:
        Ressource FHIR : liste_profils.html
        Ressource CDA : ressource_cda.html
    Annexes: 
        Glossaire: annexes_Glossaire.html
        Nomenclatures de référence:  annexes_Nomenclature.html
        Nomenclature précision de l'orientation: annexes_Nomenclatures_precision.html
        OID MDPH : annexes_OID_MDPH.html        
        Diagramme de séquence SI-MDPH/SI-SDO/-SI-ESMS: annexes_Diagramme.html
    Autres ressources:
        Sécurité: securite.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/
