canonical: https://interop.esante.gouv.fr/ig/fhir/sdo
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false
id: ans.fhir.fr.sdo
name: SuiviDecisionsOrientation
status: active
version: 4.0.2-ballot-2
dependencies:
  ans.fr.nos:
    version: 1.1.0
    uri: https://interop.esante.gouv.fr/ig/nos/ImplementationGuide/ans.fr.nos
    id: ans_fr_nos
